version: '3'
services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid-container
    ports:
      - "3128:3128"
    volumes:
      - ./squid/:/etc/squid/
      - squid-logs:/var/log/squid
      - squid-cache:/var/spool/squid

volumes:
  squid-logs:
  squid-cache: